/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f401xe.h"

#include "main.h"
#include "button.h"
#include "led.h"


// For 32-bit Cortex M4 is atomic, if this
// were 64 bit we would need protection
volatile uint32_t tick = 0;

volatile uint32_t led_activated = 1;


void SysTick_Handler(void) {
	tick++;
}

int main(void) {
	// Configure SysClock
	SysTick->LOAD = 16000 - 1;  // 1ms
	SysTick->VAL = 0;
	SysTick->CTRL = SysTick_CTRL_ENABLE_Msk
			      | SysTick_CTRL_TICKINT_Msk
				  | SysTick_CTRL_CLKSOURCE_Msk;

	// Initialize drivers
	button_init();
	led_init();

	while (1) {
		ButtonEvent button_event = button_get_event();
		switch (button_event) {
		case BUTTON_LONG_PRESS:
			led_set_state(LED_OFF);
			led_activated = !led_activated;
			break;
		case BUTTON_PRESS:
			if (led_activated) {
				led_set_state(LED_ON);
			}
			break;
		case BUTTON_RELEASE:
			if (led_activated) {
				led_set_state(LED_OFF);
			}
			break;
		case BUTTON_IDLE:
		default:
			// do-nothing
			break;
		}
	}
}
