/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "main.h"
#include "button.h"
#include "led.h"
#include "timebase.h"


volatile uint8_t led_activated = 0;


int main(void) {
	// Initialize drivers
    timebase_init();
	led_init();
    button_init();

    timer_t timer;
    int32_t period = 200;  //ms
    timer_start(&timer, period);

	while (1) {
        if (timer_expired(&timer)) {
            if (led_activated) {
                led_set_state(LED_OFF);
                led_activated = 0;
            } else {
                led_set_state(LED_ON);
                led_activated = 1;
            }

            timer_start(&timer, period);
        }

        // Logic to modify blinking rate
        ButtonEvent event = button_get_event();
        if (event == BUTTON_RELEASE) {
            period += 50;
        } else if (event == BUTTON_LONG_PRESS) {
            period -= 100;
            // Bottom out at 20ms
            if (period <= 0) {
                period = 20;
            }
        }
	}
}
