/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "main.h"
#include "led.h"
#include "timebase.h"


volatile uint8_t led_activated = 0;


int main(void) {
	// Initialize drivers
    timebase_init();
	led_init();

    timer_t timer = { get_current_time_ms(), 500 }; // 500ms

	while (1) {
        if (period_elapsed(&timer)) {
            if (led_activated) {
                led_set_state(LED_OFF);
                led_activated = 0;
            } else {
                led_set_state(LED_ON);
                led_activated = 1;
            }

            timer.start = get_current_time_ms();
        }
	}
}
