/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "main.h"
#include "button.h"
#include "led.h"
#include "timebase.h"


volatile uint8_t led_activated = 1;


int main(void) {
	// Initialize drivers
    timebase_init();
	button_init();
	led_init();

	while (1) {
		ButtonEvent button_event = button_get_event();
		switch (button_event) {
		case BUTTON_LONG_PRESS:
			led_set_state(LED_OFF);
			led_activated = !led_activated;
			break;
		case BUTTON_PRESS:
			if (led_activated) {
				led_set_state(LED_ON);
			}
			break;
		case BUTTON_RELEASE:
			if (led_activated) {
				led_set_state(LED_OFF);
			}
			break;
		case BUTTON_IDLE:
		default:
			// do-nothing
			break;
		}
	}
}
